# Generated by Django 5.1 on 2024-08-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.IntegerField()),
                ('segment_name', models.CharField(max_length=255)),
                ('completed_month', models.CharField(max_length=50)),
                ('data_correction_done', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=255)),
                ('research_group_head', models.CharField(max_length=255)),
                ('contact_person_in_research', models.CharField(max_length=255)),
                ('analysis_group_head', models.CharField(max_length=255)),
                ('contact_person_in_analysis', models.CharField(max_length=255)),
                ('expected_date_of_output', models.CharField(max_length=255)),
                ('actual_final_output', models.CharField(max_length=255)),
            ],
        ),
    ]
