# Generated by Django 5.1 on 2024-08-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='actual_final_output',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='analysis_group_head',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='completed_month',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='contact_person_in_analysis',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='contact_person_in_research',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='data_correction_done',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='expected_date_of_output',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='research_group_head',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='segment_name',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='status',
        ),
    ]
