# Generated by Django 5.1 on 2024-08-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0003_remove_segment_item_remove_segment_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='actual_final_output',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='analysis_group_head',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='completed_month',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='contact_person_in_analysis',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='contact_person_in_research',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='data_correction_done',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='expected_date_of_output',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='research_group_head',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='segment_name',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='status',
        ),
        migrations.AddField(
            model_name='segment',
            name='item',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='segment',
            name='segment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='segment',
            name='value',
            field=models.TextField(default=''),
        ),
    ]
