# Generated by Django 5.1 on 2024-08-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0004_remove_segment_actual_final_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='segment_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
