# Generated by Django 5.1 on 2024-08-27 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0006_alter_segment_item_alter_segment_segment_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='item',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='value',
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='SegmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_items', to='segments.segment')),
            ],
        ),
    ]
