# Generated by Django 5.1 on 2024-08-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0009_remove_segment_item_remove_segment_segment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='check_list_followed',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='feedback_survey_done',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
