# Generated by Django 5.1 on 2024-08-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0011_alter_segment_analysis_group_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='achieved_sample_size',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='actual_sample_size',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='advanced_analytics',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='ap_received_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='archive_taken',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='date_of_awn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='date_of_r_awn1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='date_of_r_awn2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='date_of_r_awn3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='dp_platform',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='final_processed_samples',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='fw_end_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='fw_start_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='loi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='norms_done',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='number_of_response',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='oe_coding',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='oe_costing',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='project_classification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='question_received_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='remarks',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='survey_platform',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='top_lines',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='analysis_group_head',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
