# Generated by Django 5.1 on 2024-08-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0013_segment_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='client',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='job_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='month',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='project_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
