# Generated by Django 5.1 on 2024-09-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0014_segment_client_segment_job_number_segment_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='combined_values',
            field=models.TextField(blank=True, null=True),
        ),
    ]
