# Generated by Django 5.1 on 2024-09-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0015_segment_combined_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='combined_values',
        ),
    ]
