# Generated by Django 5.1 on 2024-09-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0016_remove_segment_combined_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='segment_number',
        ),
    ]
