# Generated by Django 5.1 on 2024-09-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0017_remove_segment_segment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='segment_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
