# Generated by Django 5.1 on 2024-09-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0019_remove_segment_segment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='segment_number',
            field=models.IntegerField(null=True),
        ),
    ]
