# Generated by Django 5.1 on 2024-09-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0020_segment_segment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='segment_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
