# Generated by Django 5.1 on 2024-09-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0022_alter_segment_segment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='date_of_r_awn1',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='date_of_r_awn2',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='date_of_r_awn3',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='question_received_date',
            field=models.DateField(max_length=255, null=True),
        ),
    ]
