# Generated by Django 5.1 on 2024-09-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0024_rename_question_received_date_segment_questionnaire_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='date_of_r_awn1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='date_of_r_awn2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='date_of_r_awn3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='questionnaire_received_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
