# Generated by Django 5.1 on 2024-09-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0026_rename_date_of_r_awn1_segment_date_of_rawn1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='date_of_rawn1',
            new_name='date_of_r_awn1',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='date_of_rawn2',
            new_name='date_of_r_awn2',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='date_of_rawn3',
            new_name='date_of_r_awn3',
        ),
    ]
