# Generated by Django 5.1 on 2024-09-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0027_rename_date_of_rawn1_segment_date_of_r_awn1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='segment_number',
            field=models.IntegerField(null=True),
        ),
    ]
