# Generated by Django 5.1 on 2024-09-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0028_alter_segment_segment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='segment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
