# Generated by Django 5.1 on 2024-09-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0029_alter_segment_segment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='number_of_segments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
