# Generated by Django 5.1 on 2024-09-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0030_segment_number_of_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='number_of_segments',
        ),
    ]
