# Generated by Django 5.1 on 2024-10-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0031_remove_segment_number_of_segments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='date_of_r_awn2',
            new_name='final_r_awn',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='date_of_r_awn3',
            new_name='top_lines_date',
        ),
    ]
