from django.db import models

class Segment(models.Model):
    segment_number = models.IntegerField(null=True, blank=True)
    unit = models.CharField(max_length=255, null=True)
    year = models.CharField(max_length=255, null=True)
    month = models.CharField(max_length=255, null=True)
    project_name = models.CharField(max_length=255, null=True)
    job_number = models.CharField(max_length=255, null=True)
    client = models.CharField(max_length=255, null=True)
    segment_name = models.CharField(max_length=255, null=True)
    completed_month = models.CharField(max_length=50, null=True)
    data_correction_done = models.CharField(max_length=3, null=True)
    status = models.CharField(max_length=255, null=True)
    research_group_head = models.CharField(max_length=255, null=True)
    contact_person_in_research = models.CharField(max_length=255, null=True)
    analysis_group_head = models.CharField(max_length=255, null=True)  
    contact_person_in_analysis = models.CharField(max_length=255, null=True)
    expected_date_of_output = models.CharField(max_length=255, null=True)
    actual_final_output = models.CharField(max_length=255, null=True)
    check_list_followed = models.CharField(max_length=255, null=True)
    feedback_survey_done = models.CharField(max_length=255, null=True)
    remarks = models.CharField(max_length=255, null=True)
    archive_taken = models.CharField(max_length=255, null=True)
    loi = models.CharField(max_length=255, null=True)
    number_of_response = models.CharField(max_length=255, null=True)
    oe_costing = models.CharField(max_length=255, null=True)
    oe_coding = models.CharField(max_length=255, null=True)
    top_lines = models.CharField(max_length=255, null=True)
    fw_end_date = models.CharField(max_length=255, null=True)
    fw_start_date = models.CharField(max_length=255, null=True)
    ap_received_date = models.CharField(max_length=255, null=True)
    questionnaire_received_date = models.CharField(max_length=255, null=True)
    top_lines_date = models.CharField(max_length=255, null=True)
    final_r_awn = models.CharField(max_length=255, null=True)
    date_of_r_awn1 = models.CharField(max_length=255, null=True)
    date_of_awn = models.CharField(max_length=255, null=True)
    final_processed_samples = models.CharField(max_length=255, null=True)
    achieved_sample_size = models.CharField(max_length=255, null=True)
    actual_sample_size = models.CharField(max_length=255, null=True)
    advanced_analytics = models.CharField(max_length=255, null=True)
    norms_done = models.CharField(max_length=255, null=True)
    survey_platform = models.CharField(max_length=255, null=True)
    dp_platform = models.CharField(max_length=255, null=True)
    project_classification = models.CharField(max_length=255, null=True)


    def __str__(self):
        return f"Segment {self.segment_number}: {self.segment_name}"
