# Generated by Django 5.0.6 on 2024-09-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_survey_survey_responses_survey_q1_survey_q2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='in_charge',
            new_name='dp_in_charge',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='in_charge1',
            new_name='scripting_in_charge',
        ),
    ]
